#!/usr/bin/env node
import fs from 'node:fs';
import crypto from 'node:crypto';
import {ImapFlow} from 'imapflow';
import {simpleParser} from 'mailparser';
import {classifyReply,matchCandidate,messageFingerprint,normalizeSubject,safeExcerpt} from '../tools/camping-mail-core.mjs';
import {draftBody,draftSubject} from '../tools/camping-mail-templates.mjs';

const ROOT=new URL('../',import.meta.url),OWNER=`github-${process.env.GITHUB_RUN_ID||'manual'}-${process.pid}`,LEASE_MS=12*60*1000;
const mode=String(process.env.MAIL_RUNNER_MODE||'disabled').toLowerCase();
const nowIso=()=>new Date().toISOString();
const RUN_HOURS_UTC=[6,12,18];
const nextRun=()=>{const now=new Date();for(const hour of RUN_HOURS_UTC){const d=new Date(now);d.setUTCHours(hour,0,0,0);if(d>now)return d.toISOString();}const d=new Date(now);d.setUTCDate(d.getUTCDate()+1);d.setUTCHours(RUN_HOURS_UTC[0],0,0,0);return d.toISOString();};
const cleanHeader=v=>String(v||'').replace(/[\r\n]+/g,' ').trim();

function cloudUrl(){const src=fs.readFileSync(new URL('app.js',ROOT),'utf8'),url=src.match(/CLOUD_URL\s*=\s*'([^']+)'/)?.[1];if(!url)throw new Error('Firebase-Konfiguration fehlt');return url;}
async function readState(){const r=await fetch(cloudUrl(),{headers:{'X-Firebase-ETag':'true'},cache:'no-store'});if(!r.ok)throw new Error(`Firebase GET ${r.status}`);return {state:await r.json(),etag:r.headers.get('etag')};}
function stamp(state){state.meta=state.meta||{};const old=Date.parse(state.meta.lastSaved||'')||0;state.meta.lastSaved=new Date(Math.max(Date.now(),old+1)).toISOString();}
async function updateState(mutator){for(let i=0;i<3;i++){const {state,etag}=await readState();const changed=await mutator(state);if(!changed)return state;stamp(state);const r=await fetch(cloudUrl(),{method:'PUT',headers:{'Content-Type':'application/json','if-match':etag},body:JSON.stringify(state)});if(r.status===412)continue;if(!r.ok)throw new Error(`Firebase PUT ${r.status}`);return state;}throw new Error('Firebase-Konflikt nach 3 Versuchen');}
function assistant(state){const a=state.mailAssistant||(state.mailAssistant={});a.processedMessageIds=Array.isArray(a.processedMessageIds)?a.processedMessageIds:[];a.draftRequests=Array.isArray(a.draftRequests)?a.draftRequests:[];a.reviewQueue=Array.isArray(a.reviewQueue)?a.reviewQueue:[];a.shadowResults=Array.isArray(a.shadowResults)?a.shadowResults:[];a.runners=a.runners||{};a.runners.cloud=a.runners.cloud||{};return a;}
function candidates(state){const places=new Map((state.sleepPlaces||[]).map(p=>[p.id,p]));return (state.sleepSearches||[]).flatMap(search=>(search.candidates||[]).map(candidate=>{const p=places.get(candidate.placeId)||{};return {searchId:search.id,candidateId:candidate.id,name:p.name||candidate.name,email:p.email||candidate.email,threadSubject:candidate.mailThreadSubject||'',dateLabel:search.dateLabel};}));}
function locate(state,event){const search=(state.sleepSearches||[]).find(x=>x.id===event.searchId),candidate=search?.candidates?.find(x=>x.id===event.candidateId),place=(state.sleepPlaces||[]).find(x=>x.id===candidate?.placeId);return {search,candidate,place};}
function syncDerived(state,search,candidate,place){
  candidate.reminderId=null;
}
function logMailChange(state,name,desc='ausgewertet'){state.log=Array.isArray(state.log)?state.log:[];state.log.push({id:`mail-${crypto.randomUUID()}`,ts:nowIso(),who:'Mail-Assistent',desc:`hat die Antwort von „${name}“ ${desc}`,undo:null});state.log=state.log.slice(-60);}
async function acquireLease(){let acquired=false;await updateState(state=>{const a=assistant(state),until=Date.parse(a.lease?.expiresAt||'');if(until>Date.now()&&a.lease.owner!==OWNER)return false;a.lease={owner:OWNER,expiresAt:new Date(Date.now()+LEASE_MS).toISOString()};acquired=true;return true;});if(!acquired)throw new Error('Ein anderer Mail-Check läuft bereits');}
async function releaseLease(error=''){await updateState(state=>{const a=assistant(state),r=a.runners.cloud;a.runnerMode=mode;r.lastRunAt=nowIso();r.nextRunAt=nextRun();if(error)r.lastError=error;else{r.lastSuccessAt=r.lastRunAt;r.lastError='';}if(a.lease?.owner===OWNER)a.lease=null;return true;});}
function addressOf(list=[]){return list?.[0]?.address||'';}
function chooseMailbox(list,special,fallback){return list.find(x=>x.specialUse===special)?.path||list.find(x=>fallback.test(x.path))?.path||'';}
async function envelopes(client,path,sinceDays=45){if(!path)return [];const lock=await client.getMailboxLock(path,{readOnly:true});try{const ids=await client.search({since:new Date(Date.now()-sinceDays*86400000)},{uid:true});const chosen=ids.slice(-120),out=[];if(!chosen.length)return out;for await(const m of client.fetch(chosen.join(','),{uid:true,envelope:true,internalDate:true,size:true},{uid:true}))out.push(m);return out;}finally{lock.release();}}
async function sourceFor(client,path,uid){const lock=await client.getMailboxLock(path,{readOnly:true});try{return (await client.fetchOne(uid,{source:true},{uid:true}))?.source||Buffer.alloc(0);}finally{lock.release();}}
function draftMessageId(requestId){return `<sizigia-${crypto.createHash('sha256').update(String(requestId||'')).digest('hex').slice(0,32)}@draft.invalid>`;}
function rawDraft({from,to,subject,body,inReplyTo,messageId}){const enc=`=?UTF-8?B?${Buffer.from(cleanHeader(subject)).toString('base64')}?=`,id=cleanHeader(messageId)||`<sizigia-${crypto.randomUUID()}@local.invalid>`,refs=inReplyTo?`In-Reply-To: ${cleanHeader(inReplyTo)}\r\nReferences: ${cleanHeader(inReplyTo)}\r\n`:'';return Buffer.from(`From: ${cleanHeader(from)}\r\nTo: ${cleanHeader(to)}\r\nSubject: ${enc}\r\nDate: ${new Date().toUTCString()}\r\nMessage-ID: ${id}\r\n${refs}MIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n${String(body).replace(/\r?\n/g,'\r\n')}`);}
async function connectIcloud(){const email=process.env.ICLOUD_EMAIL,users=[email.split('@')[0],email].filter((x,i,a)=>x&&a.indexOf(x)===i);for(const user of users){const client=new ImapFlow({host:'imap.mail.me.com',port:993,secure:true,auth:{user,password:process.env.ICLOUD_APP_PASSWORD},logger:false,disableAutoIdle:true});try{await client.connect();return client;}catch{await client.logout().catch(()=>{});}}throw new Error('iCloud-Anmeldung fehlgeschlagen; App-Passwort oder Adresse prüfen');}
async function collectInbox(client,inbox,state){const all=candidates(state),processed=new Set(assistant(state).processedMessageIds),envs=await envelopes(client,inbox),events=[];for(const m of envs){const id=m.envelope?.messageId||`uid:${m.uid}`;if(processed.has(id))continue;const matched=matchCandidate({from:addressOf(m.envelope?.from),subject:m.envelope?.subject||''},all);if(!matched)continue;const raw=await sourceFor(client,inbox,m.uid);const mail=await simpleParser(raw,{skipImageLinks:true,maxHtmlLengthToParse:200000});const result=classifyReply(mail.text||'');events.push({...matched,messageId:id,receivedAt:(m.internalDate||mail.date||new Date()).toISOString(),subject:m.envelope?.subject||'',result});}return events;}
async function createDrafts(client,draftsPath,state){if(mode!=='cloud'||!draftsPath)return [];const events=[],existingIds=new Set((await envelopes(client,draftsPath)).map(m=>cleanHeader(m.envelope?.messageId)));for(const req of assistant(state).draftRequests.filter(x=>x.status==='requested')){const found=locate(state,req);if(!found.candidate||!found.search)continue;const to=found.place?.email||found.candidate.email;if(!to)continue;const body=draftBody(state,found.search,found.candidate,found.place,req.template),subject=draftSubject(found.search,{...found.candidate,name:found.place?.name||found.candidate.name},req.template),messageId=draftMessageId(req.id);if(!existingIds.has(messageId)){await client.append(draftsPath,rawDraft({from:process.env.ICLOUD_EMAIL,to,subject,body,inReplyTo:req.messageId,messageId}),['\\Draft']);existingIds.add(messageId);}events.push({type:'draft',requestId:req.id,readyAt:nowIso()});}return events;}
async function detectSent(client,sentPath,state){if(mode!=='cloud'||!sentPath)return [];const envs=await envelopes(client,sentPath,20),events=[];for(const req of assistant(state).draftRequests.filter(x=>x.status==='ready')){const {search,candidate,place}=locate(state,req);if(!candidate||!search)continue;const email=(place?.email||candidate.email||'').toLowerCase(),subject=normalizeSubject(draftSubject(search,{...candidate,name:place?.name||candidate.name},req.template)),created=Date.parse(req.createdAt||0);const hit=envs.find(m=>Date.parse(m.internalDate||0)>=created&&addressOf(m.envelope?.to).toLowerCase()===email&&normalizeSubject(m.envelope?.subject||'')===subject);if(hit)events.push({type:'sent',requestId:req.id,searchId:req.searchId,candidateId:req.candidateId,sentAt:(hit.internalDate||new Date()).toISOString()});}return events;}
async function applyEvents(events){return updateState(state=>{
  const a=assistant(state);
  for(const e of events){
    if(e.type==='draft'){const req=a.draftRequests.find(x=>x.id===e.requestId);if(req&&req.status==='requested'){req.status='ready';req.readyAt=e.readyAt;}continue;}
    if(e.type==='sent'){const req=a.draftRequests.find(x=>x.id===e.requestId),{search,candidate,place}=locate(state,e);if(req&&candidate&&req.status==='ready'){const policy=['network_policy','inquiry','followup'].includes(req.template);req.status='sent_detected';req.sentAt=e.sentAt;candidate.status=policy?'awaiting':'reserving';candidate.draftState='sent';candidate.contactedAt=e.sentAt;candidate.nextAction=policy?'Auf Antwort warten':'Auf definitive Bestätigung warten';syncDerived(state,search,candidate,place);logMailChange(state,place?.name||candidate.name,'als gesendet erkannt');}continue;}
    if(!e.result)continue;
    if(e.messageId&&a.processedMessageIds.includes(e.messageId))continue;
    if(mode==='shadow'){const key=messageFingerprint(e.messageId);if(!a.shadowResults.some(x=>x.messageFingerprint===key))a.shadowResults.push({messageFingerprint:key,candidateId:e.candidateId,predictedStatus:e.result.status,at:nowIso()});continue;}
    const {search,candidate,place}=locate(state,e);if(!candidate)continue;
    if(e.result.status==='review'||e.result.status==='booked'){const id=messageFingerprint(e.messageId);if(!a.reviewQueue.some(x=>x.id===id))a.reviewQueue.push({id,messageIdHash:id,searchId:e.searchId,candidateId:e.candidateId,campsiteName:place?.name||candidate.name,dateLabel:search.dateLabel,receivedAt:e.receivedAt,subject:e.subject,excerpt:safeExcerpt(e.result.excerpt,600),suggestedStatus:e.result.status==='booked'?'booked':'',status:'pending'});logMailChange(state,place?.name||candidate.name,'zur Prüfung vorgemerkt');}
    else{candidate.status=e.result.status;candidate.reply=e.result.summary;candidate.replyQuote=e.result.replyQuote;candidate.nextAction=e.result.nextAction;candidate.repliedAt=e.receivedAt;candidate.mailMessageId=e.messageId;candidate.mailThreadSubject=e.subject;syncDerived(state,search,candidate,place);logMailChange(state,place?.name||candidate.name);}
    if(!a.processedMessageIds.includes(e.messageId))a.processedMessageIds.push(e.messageId);
  }
  a.processedMessageIds=a.processedMessageIds.slice(-500);a.reviewQueue=a.reviewQueue.slice(-50);a.shadowResults=a.shadowResults.slice(-50);return true;
});}
async function main(){if(!['shadow','cloud'].includes(mode)){console.log(JSON.stringify({ok:true,disabled:true}));return;}for(const key of ['ICLOUD_EMAIL','ICLOUD_APP_PASSWORD'])if(!process.env[key])throw new Error(`${key} fehlt`);await acquireLease();let client,error='';try{const {state}=await readState();client=await connectIcloud();const boxes=await client.list(),inbox=chooseMailbox(boxes,'\\Inbox',/^inbox$/i)||'INBOX',sent=chooseMailbox(boxes,'\\Sent',/sent|gesendet/i),drafts=chooseMailbox(boxes,'\\Drafts',/draft|entwurf/i);const inbound=await collectInbox(client,inbox,state),draftEvents=await createDrafts(client,drafts,state),sentEvents=await detectSent(client,sent,state);await applyEvents([...inbound,...draftEvents,...sentEvents]);console.log(JSON.stringify({ok:true,mode,matched:inbound.length,drafts:draftEvents.length,sent:sentEvents.length}));}catch(e){error=String(e.message||e);throw e;}finally{if(client)await client.logout().catch(()=>{});await releaseLease(error).catch(()=>{});}}

if(process.argv.includes('--self-test')){const messageId=draftMessageId('req-self-test'),raw=rawDraft({from:'a@icloud.com',to:'b@example.com',subject:'Test – 02.–03.08.',body:'Kind regards,\n\n',inReplyTo:'<old@example.com>',messageId}).toString();if(!raw.includes('In-Reply-To: <old@example.com>')||!raw.includes(`Message-ID: ${messageId}`)||!raw.endsWith('Kind regards,\r\n\r\n')||draftMessageId('req-self-test')!==messageId)throw new Error('Draft self-test failed');console.log(JSON.stringify({ok:true,blankSignature:true,threadHeaders:true,idempotentDraftId:true}));}
else main().catch(e=>{console.error(JSON.stringify({ok:false,error:String(e.message||e)}));process.exitCode=1;});
